name: rpxdock
channels:
 - conda-forge
 - https://conda.anaconda.org/t/IuO94WfD-JCG/rosettacommons
dependencies:
 - python>=3.7
 - pyrosetta=2018.52
 - numpy=1.16.3
 - matplotlib
 - pandas=0.24.2
 - xarray=0.11.3
 - pytest
 - pytest-faulthandler
 - ipython
 - cffi
 - tqdm
 - yapf
 - pytest-sugar
 - pytest-xdist
 - tabulate
 - pip

 - pip:
   - homog >= 0.1.10
   - xbin >= 0.1.5
   - cppimport

